tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "jaredboone/versions"
brew "ansible"
brew "dockutil"
brew "git"
brew "wget"
brew "zsh"
brew "zsh-completions"
cask "appcleaner"
cask "ccleaner"
cask "cheatsheet"
cask "firefox"
cask "github"
cask "google-chrome"
cask "inboxer"
cask "iterm2"
cask "macpass"
cask "muzzle"
cask "slack"
cask "sublime-text"
cask "visual-studio-code"
cask "vagrant"
#requires sudo
cask "malwarebytes"

# fails due to Security Prompt
# cask "virtualbox"

# fails due to App Store changes
#brew "mas"
#mas "Bear", id: 1091189122
#mas "Time Out", id: 402592703
